language: python
python:
    - "3.7"
    - "3.6"
install:
    - pip install .
    - pip install pytest
    - pip install pytest-cov
    - pip install codecov
script:
    - pytest --cov=./
after_success: codecov