# appveyor.yml
image:
    - Visual Studio 2019
environment:
    matrix:
        - PYTHON: "C:\\Python37-x64"
        - PYTHON: "C:\\Python36-x64"

build: off

install:
    - "%PYTHON%\\python.exe -m pip install .[dev]"

test_script:
    - "%PYTHON%\\python.exe -m pytest"