# appveyor.yml
image:
    - Visual Studio 2019
environment:
    matrix:
        - PYTHON: "C:\\Python37-x64"
        - PYTHON: "C:\\Python36-x64"

build: off

install:
    - "%PYTHON%\\python.exe -m pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html"
    - "%PYTHON%\\python.exe -m pip install .[dev]"

test_script:
    - "%PYTHON%\\python.exe -m pytest"